project_id = "xlyxtbcqirspcfxdznyu"

[functions.mailerlite-sync]
verify_jwt = false

[functions.create-payfast-checkout]
verify_jwt = false

[functions.shipday-updates]
verify_jwt = false

[functions.post-to-shipday]
verify_jwt = false

[functions.routine-maintenance]
verify_jwt = false
